config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :recipes
  resources :favourites, only: [:create, :destroy, :index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#index"

  get '/my_recipes', to: 'recipes#my_recipes'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :favourites, dependent: :destroy
    has_many :favourited_by_users, through: :favourites, source: :user
    has_one_attached :image

    # Form Validations    
    validates :name, presence: true
    validates :description, presence: true
    # validates :name, presence: true

    def self.search(params)
        params[:query].blank? ? all : where(
            "name LIKE?", "%#{sanitize_sql_like(params[:query])}%"
        )
    end    
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.search(params)
    # @myrecipes = @recipes.where(user_id: current_user.id)
  end

  def my_recipes
    @recipes = current_user.recipes
  end
  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    if @recipe.user == current_user
      respond_to do |format|
        if @recipe.update(recipe_params)
          format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
          format.json { render :show, status: :ok, location: @recipe }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to recipes_url, alert: "You can only update your own recipes."
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :category, :cooktime, :serving, :healthrating, :difficulty, :image)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: "contents") do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, :default => "favourite.svg" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.select :category,[["Breakfast"], ["Lunch"],["Dinner"],["Sweet Treats"],["Snacks"] ], class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

<div class="my-5">
    <%= form.label :serving_size %>
    <%= form.select :serving,[["1-2"],["2-4"],["4-6"],["6-8",],["8-10"],["10+"]], class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cooktime %>
    <%= form.number_field :cooktime, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
   
  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, class: "tinymce", triggerSave: true  %>
    <%= tinymce %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/recipes/_recipe-card.html.erb
<div id="recipe-card">
  <%= link_to recipe, data: { turbo_frame: "_top" } do %>
    <div id="recipe-thumbnail">
      <% if recipe.image.attached? %>
        <%= image_tag recipe.image, alt: recipe.name, class: "recipe-image" %>
      <% else %>
        <%= image_tag "empty.svg", alt: recipe.name, class: "recipe-image" %>
      <% end %>
    </div>  
  <% end %>
   <h2><%= recipe.name %></h2>
  <h3> By <%= recipe.user.username %></h3>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" data-controller= "share" data-share-url-value="<%= recipe_url(recipe) %>">
  <% if recipe.image.attached? %>
    <%= image_tag recipe.image, alt: recipe.name, class: "recipe-image" %>
  <% end %>
  
  
  <p class="my-5">
    <%= content_tag(:p, recipe.name, id:"recipe-name", data: {
      share_target: "name"
    }) %>
  </p>
  
  <div class="username">
    <%= recipe.user.username %>
  </div>

  
  <p class="my-5">
    <%= recipe.description %>
  </p>
  
<div class ="stats">
  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= recipe.category %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Cooktime:</strong>
    <%= recipe.cooktime %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Serving:</strong>
    <%= recipe.serving %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Healthrating:</strong>
    <%= recipe.healthrating %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Difficulty:</strong>
    <%= recipe.difficulty %>
  </p>

</div>
  <% if action_name != "show" %>
    <%= link_to "Show", recipe, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% if recipe.user == current_user %>
        <%= link_to 'Edit', edit_recipe_path(recipe), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>    
    <hr class="mt-6">
  <% end %>
  <div class="share-btn">
    <%= image_tag "share.svg", alt: "share" %>
    <%= button_to  "Share", "", data: {
      action: "click->share#share"
    } %>

    <%= content_tag(:p, "", class: "result", data: {
      share_target: "result"
    }) %>
  </div>  
</div>

app/views/recipes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing recipe</h1>

  <%= render "form", recipe: @recipe %>

  <%= link_to "Show this recipe", @recipe, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to recipes", recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/recipes/index.html.erb
<div class="flex-row pl-10" id="collapse">
  <div class="recipe-header">
    <h1>Discover Recipes</h1>
  </div>
  <div class="recipe-forms flex items-center mb-2 mt-4">
    <%= link_to 'New recipe', new_recipe_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium mr-2" %>
    <%= form_with(url: recipes_path, method: :get, data: { 
        turbo_frame: "recipes", 
        turbo_action: "advance", 
        controller: "search",
        action: "input->search#search"
        }) do |f| %>
      <%= text_field_tag :query, nil, placeholder: "Search ...", class: "rounded ml-2" %>
      <%= submit_tag "", class: "btn" %>
    <% end %>
  </div>
  <%= turbo_frame_tag "recipes" do %>
  <%= render partial: 'recipes/recipe-card', collection: @recipes, as: :recipe %>
<% end %>
</div>

app/views/recipes/my_recipes.html.erb
<div class="flex-row pl-10">
  <div class="recipe-header">
    <h1>My Recipes</h1>
  </div>
    <div class="recipe-forms flex items-center mb-2 mt-4">
      <%= link_to 'New recipe', new_recipe_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  <%= turbo_frame_tag "recipes" do %>
    <%= render partial: 'recipes/recipe-card', collection: @recipes, as: :recipe %>
  <% end %>
</div>  

app/views/recipes/new.html.erb
<div id="new-recipe-form" class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Add recipe</h1>

  <%= render "form", recipe: @recipe %>

  <%= link_to 'Back to recipes', recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/recipes/show.html.erb
<div id ="recipe-listing">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= render @recipe %>


  <% if @recipe.user == current_user %>
    <div class= "edit-btn">
      <%= image_tag "edit.svg", alt: "edit" %>
      <%= link_to 'Edit', edit_recipe_path(@recipe) %>
    </div> 
  <% end %>

  <div class= "fav-btn"> 
    <% if user_signed_in? %>
      <% if current_user.favourites.exists?(recipe_id: @recipe.id) %>
        <%= turbo_frame_tag "favourite" do %>
          <%= button_to favourite_path(recipe_id: @recipe.id), method: :delete, class: "unbookmark" do %>
            <%= image_tag "unfavourite.svg", alt: "Unfavourite" %>
            <p style="color:#e44650;"> Unfavourite </p>
          <% end %>
        <% end %>
      <% else %>
        <%= turbo_frame_tag "favourite" do %>
          <%= button_to favourites_path(recipe_id: @recipe.id), class: "bookmark", method: :post do %>
            <%= image_tag "favourite.svg", alt: "Favourite" %>
            <p style="color:#4010de;"> Favourite </p>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <% if @recipe.user == current_user %>
    <div class="delete-btn">
      <%= image_tag "delete.svg", alt: "delete" %> 
      <%= button_to 'Delete', recipe_path(@recipe), method: :delete %>
    </div>
  <% end %>
  <%= link_to 'Back to recipes', recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 font-medium", style:"width: fit-content; margin-left:0;" %>
</div>